import { SynthesizerProvider } from "./synthesizer";

export class MockProvider implements SynthesizerProvider {
    async generatePlayIR(prompt: string): Promise<string> {
        return `
schema_version: "1.0.0"
operation_id: "mock_operation"
metadata:
  description: "Mocked play generated by fallback provider"
  author: "synaptic-pruner"
  deterministic: true
actions:
  - id: "step_1"
    runtime: "fs"
    action: "make_directory"
    target: "{{inputs.cwd}}/mock_dir"
`;
    }
}
