import { SynthesizerProvider } from "./synthesizer";

export class MockProvider implements SynthesizerProvider {
    async generatePlayIR(prompt: string): Promise<string> {
        let nodes: any[] = [];
        const nodesMatch = prompt.match(/## Causal Trace \(To Translate\)\n([\s\S]*?)\n## Resource Classifications/);
        if (nodesMatch) {
            try {
                nodes = JSON.parse(nodesMatch[1]);
            } catch (e) {}
        }
        
        const actionsStr = nodes.map((n, i) => {
            return `  - id: "step_${i + 1}"
    runtime: "shell"
    command: ${JSON.stringify(n.command)}
    provenance:
      sourceNodeIds: ["${n.id}"]`;
        }).join("\n");
        
        return `
schema_version: "1.0.0"
operation_id: "mock_operation"
metadata:
  description: "Mocked play generated by fallback provider"
  author: "synaptic-pruner"
  deterministic: true
${nodes.length > 0 ? "actions:\n" + actionsStr : "actions: []"}
`;
    }
}
